package:
  name: pyembree
  version: 0.1.4

source:
  #fn: cymetric-src.tar.gz  # ["TRAVIS" not in environ]
  #url: https://github.com/scopatz/pyembree/archive/master.tar.gz # ["TRAVIS" not in environ]
  #path: ../.. # ["TRAVIS" in environ]
  path: ../..

requirements:
   build:
    - embree
    - python
    - cython
    - numpy
    - setuptools
   run:
    - embree
    - python
    - numpy


about:
  home:
  license: BSD 2 Clause
